[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
solc = "0.8.26"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
bsc = "${BSC_RPC_URL}"
tbsc = "${BSC_TESTNET_RPC_URL}"
